spring.application.name=AIChatbot

spring.datasource.url=jdbc:postgresql://localhost:5432/aichatbot
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
