CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT chk_users_role CHECK (role IN ('MEMBER', 'ADMIN'))
);

CREATE INDEX idx_users_deleted_at ON users (deleted_at);

CREATE TABLE chat_threads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_threads_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_threads_user_id ON chat_threads (user_id);
CREATE INDEX idx_threads_deleted_at ON chat_threads (deleted_at);

CREATE TABLE chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    model VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_chats_thread FOREIGN KEY (thread_id) REFERENCES chat_threads (id),
    CONSTRAINT fk_chats_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_chats_thread_id ON chats (thread_id);
CREATE INDEX idx_chats_user_created ON chats (user_id, created_at DESC);
CREATE INDEX idx_chats_created_at ON chats (created_at);
CREATE INDEX idx_chats_deleted_at ON chats (deleted_at);

CREATE TABLE feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    is_positive BOOLEAN NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_feedbacks_chat FOREIGN KEY (chat_id) REFERENCES chats (id),
    CONSTRAINT fk_feedbacks_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_feedbacks_user_chat UNIQUE (user_id, chat_id),
    CONSTRAINT chk_feedbacks_status CHECK (status IN ('pending', 'resolved'))
);

CREATE INDEX idx_feedbacks_user_id ON feedbacks (user_id);
CREATE INDEX idx_feedbacks_is_positive ON feedbacks (is_positive);
CREATE INDEX idx_feedbacks_status ON feedbacks (status);
CREATE INDEX idx_feedbacks_deleted_at ON feedbacks (deleted_at);

CREATE TABLE activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_activity_logs_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_activity_logs_type CHECK (type IN ('SIGNUP', 'LOGIN', 'CHAT_CREATED'))
);

CREATE INDEX idx_activity_type_created ON activity_logs (type, created_at);
CREATE INDEX idx_activity_created_at ON activity_logs (created_at);
