CREATE TABLE demo_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    source_key VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_demo_documents_deleted_at ON demo_documents (deleted_at);

CREATE TABLE document_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    chunk_index INT NOT NULL,
    content TEXT NOT NULL,
    embedding TEXT,
    embedding_model VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_document_chunks_document FOREIGN KEY (document_id) REFERENCES demo_documents (id),
    CONSTRAINT uk_document_chunks_document_index UNIQUE (document_id, chunk_index)
);

CREATE INDEX idx_document_chunks_document_id ON document_chunks (document_id);
CREATE INDEX idx_document_chunks_deleted_at ON document_chunks (deleted_at);
CREATE INDEX idx_document_chunks_embedding_model ON document_chunks (embedding_model);

CREATE TABLE chat_document_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    document_chunk_id BIGINT NOT NULL,
    document_title VARCHAR(255) NOT NULL,
    chunk_index INT NOT NULL,
    score DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_document_sources_chat FOREIGN KEY (chat_id) REFERENCES chats (id),
    CONSTRAINT fk_chat_document_sources_chunk FOREIGN KEY (document_chunk_id) REFERENCES document_chunks (id)
);

CREATE INDEX idx_chat_document_sources_chat_id ON chat_document_sources (chat_id);
CREATE INDEX idx_chat_document_sources_chunk_id ON chat_document_sources (document_chunk_id);
